### ISSUE TITLE
Please use UTC in .changes files

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/KDEteam#3]
This is a reaction on the recent 'mails get too large' thread on os-factory ML

The issue is that /usr/lib/build/changelog2spec takes the first timezone entry in the file. And since the timezone there switched from CET to CEST, all dates in the rpm changelog are being recalculated (one can argue that this script is at fault, and I'll agree - but I have less hope to get this fixed quickly)

As a quick aid, to make sure this does not happen all the time (well, it will happen one more time), please force UTC as timezone onto the .changes files. Then the timezone won't switch anymore in the future.

**Comment by lbeltrame** [comment]
Fixed.
