### ISSUE TITLE
Please update kirigami2

### ISSUE THREAD

**Issue by orchyn** [openSUSE/KDEteam#5]
System settings crashes with kirigami2 5.64.0 (no problem with kirigami2  5.64.1).

**Steps to reproduce:**

 - Open System Settings => Cursors, 
 - Go Back (All Settings), and open Icons

**Distribution:**
OpenSUSE Tumbleweed Snapshot20191121 (current).

**Comment by lbeltrame** [comment]
This is not the right place to report bugs: use https://bugzilla.opensuse.org.

The fix is already on the way to Tumbleweed: https://build.opensuse.org/request/show/749979
